$$ ITI \space AI-Pro: \space Intake \space 44 $$
$$ Machine \space Learning \space 1 $$
$$ Lab \space no. \space 4 $$

# `01` Import Necessary Libraries

## `i` Default Libraries

In [ ]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

## `ii` Additional Libraries
Add imports for additional libraries you used throughout the notebook

In [ ]:
from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, f1_score, confusion_matrix
from sklearn.svm import SVC

----------------------------

# `02` Load Data

Note: Make sure the `Data` folder attached with the notebook is in the same path for this cell to work properly.

[Dataset Link](https://www.kaggle.com/datasets/parisrohan/credit-score-classification)

In [ ]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [ ]:
df = pd.read_csv('data.csv')

----------------

# `03` Exploratory Data Analysis (EDA)

## `i` Simple Analysis

Preview data, perform statistical data analysis and explore as much as needed to better understand the data set we're dealing with.

`Notes:`
- Feel free to look up EDA approaches online for inspiration (however you **must understand** everything and not copy paste).
- Make sure to add notes and insights extracted from your analysis.


## `ii` Visual Analysis

Plot graphs and relations in order to gain more insights about the data set, identify patterns, and make assumptions.

`Notes:`
- Feel free to look up visual EDA approaches online for inspiration (however you **must understand** everything and not copy paste).
- Make sure to add notes and insights extracted from your analysis.

----------------

# `04` Data Preparation

Perform data cleaning, feature engineering, scaling, dropping unwanted columns (such as IDs), etc. as needed to make sure it's ready for the model.

`Q` Is this dataset *skewed*?

Hints:
- It could be helpful to check `sklearn.preprocessing` module.
- Remember that Support Vector Machine classifiers require special preprocessing.

## `#` Prepare Test Set

Apply the data transformations you used on the training set to the test set.

**Important Note:** DO NOT use `fit` on the test set.

In [ ]:
X=df.drop('Credit_Score',axis=1)
y = df.Credit_Score

In [ ]:
X.drop(columns=['ID', 'Customer_ID', 'SSN','Unnamed: 0'], inplace= True)

In [ ]:
X

Month      Name       Age  Occupation  Annual_Income  \
0          1  1.533333  1.469375    1.368147          1.125   
1          2  1.600000  1.469375    1.368288          1.125   
2          3  1.600000  1.469375    1.368288          1.125   
3          4  1.600000  1.469375    1.368288          1.125   
4          5  1.600000  1.469375    1.368288          1.125   
...      ...       ...       ...         ...            ...   
99995      4  1.428571  1.396595    1.337980          1.500   
99996      5  1.428571  1.396595    1.337980          1.500   
99997      6  1.428571  1.396595    1.337980          1.500   
99998      7  1.714286  1.383708    1.338277          1.500   
99999      8  1.714286  1.383708    1.338277          1.500   

       Monthly_Inhand_Salary  Num_Bank_Accounts  Num_Credit_Card  \
0                2706.161667                  6         1.336984   
1                2706.161667                  6         1.336984   
2                2706.161667                  6         1.336984   
3                2706.161667                  6         1.336984   
4                2706.161667                  6         1.336984   
...                      ...                ...              ...   
99995            3749.870000                  8         1.454097   
99996            3749.870000                  8         1.454097   
99997            3749.870000                  8         1.454097   
99998            3749.870000                  8         1.454097   
99999            3749.870000                  8         1.454097   

       Interest_Rate  Num_of_Loan  ...  Num_Credit_Inquiries  Credit_Mix  \
0           1.314024            2  ...              1.398441    1.369251   
1           1.314024            2  ...              1.356203    1.369294   
2           1.314024            2  ...              1.356203    1.369294   
3           1.314024            2  ...              1.356203    1.369294   
4           1.314024            2  ...              1.356203    1.369294   
...              ...          ...  ...                   ...         ...   
99995       1.805099            6  ...              1.476322    1.670295   
99996       1.805099            6  ...              1.476322    1.670295   
99997       1.805099            6  ...              1.476322    1.670295   
99998       1.805099            6  ...              1.476322    1.670338   
99999       1.805099            6  ...              1.476322    1.670338   

       Outstanding_Debt  Credit_Utilization_Ratio  Credit_History_Age  \
0                 1.125                 26.612093            1.471264   
1                 1.125                 29.439759            1.493976   
2                 1.125                 38.285928            1.432099   
3                 1.125                 32.843081            1.457983   
4                 1.125                 32.330508            1.471963   
...                 ...                       ...                 ...   
99995             1.500                 36.384516            1.345055   
99996             1.500                 26.166508            1.338422   
99997             1.500                 36.970072            1.423181   
99998             1.500                 33.916363            1.361446   
99999             1.500                 39.916655            1.432432   

       Payment_of_Min_Amount  Total_EMI_per_month  Amount_invested_monthly  \
0                   1.531161                1.125               244.750283   
1                   1.531180                1.125               176.132567   
2                   1.531180                1.125               109.056519   
3                   1.531180                1.125                87.909909   
4                   1.531180                1.125               191.834767   
...                      ...                  ...                      ...   
99995               1.531161                1.500               234.354940   
99996              

----------------------

# `05` Linear Support Vector Machine Classifier

Using `sklearn` implementation of linear support vector machine classifiers to model the data.

Hint: Look for `sklearn.svm.LinearSVC` class.

In [ ]:
from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Step 3: Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1234)

# Step 4: Instantiate the classifier
clf = LinearSVC()

# Step 5: Train the classifier
clf.fit(X_train, y_train)

# Step 6: Evaluate the model
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

C:\Users\Hendy Group\anaconda3\Lib\site-packages\sklearn\svm\_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(


Accuracy: 0.7753


C:\Users\Hendy Group\anaconda3\Lib\site-packages\sklearn\svm\_base.py:1242: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


## `i` Baseline Model Training

Initializing the model with initial parameters, fitting it to the training data, and get a baseline model.

Use:
- `random_state` $= 1234$

In [ ]:
X_sample = X.sample(n=1000, random_state=1234)
y_sample = y.sample(n=2000, random_state=1234)

X_train, X_test, y_train, y_test = train_test_split(X_sample, y_sample, test_size=0.2, random_state=1234)

# Step 4: Initialize the classifier with initial parameters
clf = LinearSVC(random_state=1234)

# Step 5: Train the classifier
clf.fit(X_train, y_train)

# Step 6: Predict on the testing set
y_pred = clf.predict(X_test)

# Step 7: Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Baseline Model Accuracy:", accuracy)

C:\Users\Hendy Group\anaconda3\Lib\site-packages\sklearn\svm\_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(


Baseline Model Accuracy: 0.59


C:\Users\Hendy Group\anaconda3\Lib\site-packages\sklearn\svm\_base.py:1242: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


## `ii` Model Evaluation

Evaluate the baseline model performance using classification metrics, e.g. **Accuracy**, **Precision**, $F_1 \space Score$, **Confusion Matrix** etc.

Which metric is more reliable?

In [ ]:

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)

# Calculate precision
precision = precision_score(y_test, y_pred, average='weighted')

# Calculate F1 score
f1 = f1_score(y_test, y_pred, average='weighted')

# Calculate confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("F1 Score:", f1)
print("Confusion Matrix:\n", conf_matrix)


Accuracy: 0.7753
Precision: 0.8305050053467756
F1 Score: 0.727177077588446
Confusion Matrix:
 [[ 3426    49    75]
 [  106  1385  4264]
 [    0     0 10695]]


----------------------

# `06` Kernelized Support Vector Machine Classifier

Using `sklearn` implementation of kernelized support vector machine classifiers to model the data.

Hint: Look for `sklearn.svm.SVC` class.

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1234)

clf = SVC(kernel='linear', random_state=1234)

clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9938


## `i` Baseline Model Training

Initializing the model with initial parameters, fitting it to the training data, and get a baseline model.

Use:
- `random_state` $= 1234$
- `kernel` = 'linear'

## `ii` Model Evaluation

Evaluate the baseline model performance using classification metrics, e.g. **Accuracy**, **Precision**, $F_1 \space Score$, **Confusion Matrix** etc.

`Q` Which metric is more reliable?
`Q` Compare the results to those of `sklearn.svm.LinearSVC` class. Also, is there a difference in the training time?

In [ ]:

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)

# Calculate precision
precision = precision_score(y_test, y_pred, average='weighted')

# Calculate F1 score
f1 = f1_score(y_test, y_pred, average='weighted')

# Calculate confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)

print("Baseline Model:")
print("Accuracy:", accuracy)
print("Precision:", precision)
print("F1 Score:", f1)
print("Confusion Matrix:\n", conf_matrix)


Baseline Model:
Accuracy: 0.9938
Precision: 0.9938459546501607
F1 Score: 0.9938037757656737
Confusion Matrix:
 [[ 3493    53     4]
 [    0  5725    30]
 [    0    37 10658]]


In [ ]:
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, precision_score, f1_score, confusion_matrix
import time

# Instantiate and train LinearSVC model
start_time = time.time()
clf_linear = LinearSVC(random_state=1234)
clf_linear.fit(X_train, y_train)
training_time_linear_svc = time.time() - start_time

# Predictions and evaluation
y_pred_linear = clf_linear.predict(X_test)
accuracy_linear = accuracy_score(y_test, y_pred_linear)
precision_linear = precision_score(y_test, y_pred_linear, average='weighted')
f1_linear = f1_score(y_test, y_pred_linear, average='weighted')
conf_matrix_linear = confusion_matrix(y_test, y_pred_linear)

print("\nLinearSVC Model:")
print("Accuracy (LinearSVC):", accuracy_linear)
print("Precision (LinearSVC):", precision_linear)
print("F1 Score (LinearSVC):", f1_linear)
print("Confusion Matrix (LinearSVC):\n", conf_matrix_linear)
print("Training Time (LinearSVC):", training_time_linear_svc)


C:\Users\Hendy Group\anaconda3\Lib\site-packages\sklearn\svm\_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(



LinearSVC Model:
Accuracy (LinearSVC): 0.9246
Precision (LinearSVC): 0.9230574178302703
F1 Score (LinearSVC): 0.9232142489318463
Confusion Matrix (LinearSVC):
 [[ 2954   528    68]
 [  393  4879   483]
 [    0    36 10659]]
Training Time (LinearSVC): 58.45899415016174


C:\Users\Hendy Group\anaconda3\Lib\site-packages\sklearn\svm\_base.py:1242: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


## `iii` Kernelization Mode: On

Let's try the both `poly` and `rbf` kernels. Use default $C, \gamma, \space and/or \space degree$ parameter(s) for simplicity if you want. Does kernelization make the model better?

Which of the two kernels performs better?

In [ ]:


# Instantiate and train SVC model with polynomial kernel
clf_poly = SVC(kernel='poly', random_state=1234)
clf_poly.fit(X_train, y_train)

# Predictions
y_pred_poly = clf_poly.predict(X_test)

# Evaluation
accuracy_poly = accuracy_score(y_test, y_pred_poly)
precision_poly = precision_score(y_test, y_pred_poly, average='weighted')
f1_poly = f1_score(y_test, y_pred_poly, average='weighted')
conf_matrix_poly = confusion_matrix(y_test, y_pred_poly)

print("Polynomial Kernel Model:")
print("Accuracy (poly):", accuracy_poly)
print("Precision (poly):", precision_poly)
print("F1 Score (poly):", f1_poly)
print("Confusion Matrix (poly):\n", conf_matrix_poly)


Polynomial Kernel Model:
Accuracy (poly): 0.53475
Precision (poly): 0.2859575625
F1 Score (poly): 0.372643834500733
Confusion Matrix (poly):
 [[    0     0  3550]
 [    0     0  5755]
 [    0     0 10695]]


C:\Users\Hendy Group\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
# Instantiate and train SVC model with RBF kernel
clf_rbf = SVC(kernel='rbf', random_state=1234)
clf_rbf.fit(X_train, y_train)

# Predictions
y_pred_rbf = clf_rbf.predict(X_test)

# Evaluation
accuracy_rbf = accuracy_score(y_test, y_pred_rbf)
precision_rbf = precision_score(y_test, y_pred_rbf, average='weighted')
f1_rbf = f1_score(y_test, y_pred_rbf, average='weighted')
conf_matrix_rbf = confusion_matrix(y_test, y_pred_rbf)

print("\nRBF Kernel Model:")
print("Accuracy (rbf):", accuracy_rbf)
print("Precision (rbf):", precision_rbf)
print("F1 Score (rbf):", f1_rbf)
print("Confusion Matrix (rbf):\n", conf_matrix_rbf)



RBF Kernel Model:
Accuracy (rbf): 0.53555
Precision (rbf): 0.37208443438145267
F1 Score (rbf): 0.3799088585223506
Confusion Matrix (rbf):
 [[   78     0  3472]
 [   22     0  5733]
 [   62     0 10633]]


C:\Users\Hendy Group\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
print("\nComparison:")
print("Accuracy (poly):", accuracy_poly)
print("Accuracy (rbf):", accuracy_rbf)
print("Precision (poly):", precision_poly)
print("Precision (rbf):", precision_rbf)
print("F1 Score (poly):", f1_poly)
print("F1 Score (rbf):", f1_rbf)


Comparison:


NameError: name 'accuracy_poly' is not defined

## `iv` Tuning Hyperparameters

Try different  $C, \gamma, \space and/or \space degree$ values and evaluate. What is the best hyperparamters value combination?

Remember that $alpha=\frac{1}{C}$ which means less regularization for higher $C$ values.

`Hint:` Make sure to tune only relevant hyperparameters per kernel (e.g., don't tune different values for `degree` while using `rbf` kernel)

`Note:` You can tune other parameters as you see fit (but make sure you elaborate your reasoning.

Hint: You might want to use `sklearn.model_selection.RandomizedSearchCV` or `sklearn.model_selection.GridSearchCV` classes.

In [ ]:
X_sample = X.sample(n=4000, random_state=1234)
y_sample = y.sample(n=4000, random_state=1234)
# Define parameter grid for polynomial kernel
param_grid_poly = {
    'C': [0.1, 1, 10],
    'degree': [2, 3, 4]
}
X_train, X_test, y_train, y_test = train_test_split(X_sample, y_sample, test_size=0.2, random_state=1234)

# Instantiate SVC model with polynomial kernel
svc_poly = SVC(kernel='poly', random_state=1234)

# Instantiate GridSearchCV
grid_search_poly = GridSearchCV(estimator=svc_poly, param_grid=param_grid_poly, cv=3, scoring='accuracy')

# Fit GridSearchCV to training data
grid_search_poly.fit(X_train, y_train)

# Get best hyperparameters
best_params_poly = grid_search_poly.best_params_
print("Best Hyperparameters (Polynomial Kernel):", best_params_poly)

# Evaluate model with best hyperparameters
best_clf_poly = grid_search_poly.best_estimator_
y_pred_poly_tuned = best_clf_poly.predict(X_test)
accuracy_poly_tuned = accuracy_score(y_test, y_pred_poly_tuned)
print("Accuracy (Polynomial Kernel - Tuned):", accuracy_poly_tuned)

Best Hyperparameters (Polynomial Kernel): {'C': 10, 'degree': 4}
Accuracy (Polynomial Kernel - Tuned): 0.53375


In [ ]:
# Define parameter grid for RBF kernel
param_grid_rbf = {
    'C': [0.1, 1, 10],
    'gamma': ['scale', 'auto']
}

# Instantiate SVC model with RBF kernel
svc_rbf = SVC(kernel='rbf', random_state=1234)

# Instantiate GridSearchCV
grid_search_rbf = GridSearchCV(estimator=svc_rbf, param_grid=param_grid_rbf, cv=3, scoring='accuracy')

# Fit GridSearchCV to training data
grid_search_rbf.fit(X_train, y_train)

# Get best hyperparameters
best_params_rbf = grid_search_rbf.best_params_
print("Best Hyperparameters (RBF Kernel):", best_params_rbf)

# Evaluate model with best hyperparameters
best_clf_rbf = grid_search_rbf.best_estimator_
y_pred_rbf_tuned = best_clf_rbf.predict(X_test)
accuracy_rbf_tuned = accuracy_score(y_test, y_pred_rbf_tuned)
print("Accuracy (RBF Kernel - Tuned):", accuracy_rbf_tuned)

Best Hyperparameters (RBF Kernel): {'C': 10, 'gamma': 'auto'}
Accuracy (RBF Kernel - Tuned): 0.535


------------------

# `07` Generalization Error

Now that we have tuned our solution, to an *extent*, we need to test for a final time on the held out test set.

-----------------------------

# `Bonus` Better Flow

For the model to be production-ready, we need to integrate it into a pipeline along with the data preparation flow.

Hint: Look up `sklearn.pipeline.Pipeline` class.

----------------------------------------------

$$ Wish \space you \space all \space the \space best \space ♡ $$
$$ Abdelrahman \space Eid $$